-- Blog posts
DROP TABLE IF EXISTS blog_posts;
CREATE TABLE blog_posts (
	id INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL DEFAULT '',
	content TEXT NOT NULL DEFAULT '',
	PRIMARY KEY (id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
